### ISSUE TITLE
Setup greenkeeper with eslint-plugin-shopify

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#10]
Originally raised by @mikkoh [here](https://github.com/Shopify/javascript/issues/213):

> eslint-plugin-shopify has a peer dependency for eslint 3.3.x. The current version is at 3.4.x. It would be nice to have greenkeeper create Pull Requests to get updates for peer deps or locked modules. It's safe to do this... Although the way that this repo is setup as a mono package might cause issues with greenkeeper

Chris responded with this:
> I'm open to doing it, but I have a somewhat workable system of just going through every few weeks, bumping the versions on all the ESLint/ plugin dependencies, and adding configuration for all new rules as I do that.

**Comment by mikkoh** [comment]
@GoodForOneFare did you setup GreenKeeper on this repo? How was this resolved?

**Comment by GoodForOneFare** [comment]
@mikkoh nope, for now I'm just migrating issues over from the JavaScript repo.

**Comment by mikkoh** [comment]
😏 didn't see that it was a new repo til now. I think this is a good move 👍

**Comment by kaelig** [comment]
See https://github.com/Shopify/services-db/issues/1673 for current discussion on getting Probot to support npm dependencies.

**Comment by GoodForOneFare** [comment]
Closing off for now.  dependencies.io supports lerna, so Greenkeeper is no longer a slamdunk.
