### ISSUE TITLE
strict-component-boundaries error message is vague

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#122]
Violations just have a prosaic version of the rule name:
<img width="699" alt="index tsx neutron 2018-07-28 10-19-45" src="https://user-images.githubusercontent.com/673655/43357455-d86a2904-924f-11e8-9619-9898f301e6f0.png">

Users should not have to visit a rule's homepage to figure out a fix.

**Comment by cartogram** [comment]
Agree. Couldn't think of a succinct way to express the error and/or fix. Any suggestions?

Also, that particular error would go away when I implement https://github.com/Shopify/eslint-plugin-shopify/issues/123

**Comment by cartogram** [comment]
Closes via https://github.com/Shopify/eslint-plugin-shopify/pull/208
