### ISSUE TITLE
Add eslint-plugin-compat 

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#14]
https://github.com/amilajack/eslint-plugin-compat

**Comment by GoodForOneFare** [comment]
I tried out `eslint-plugin-compat` in Admin:
- The only problem that it flagged was use of `fetch` in `app/assets/javascripts/apple_pay`
- Looking at [their roadmap](https://github.com/amilajack/eslint-plugin-compat/wiki), support for Kangax isn't even in the next major release

I think it should have gone bananas when pointed at Admin with no polyfills specified, so I'm not sure this is a useful addition right now.

**Comment by lemonmade** [comment]
Cool, thanks for looking into this.
