### ISSUE TITLE
Incorrect react/no-this-in-sfc eslint failures

### ISSUE THREAD

**Issue by utkarshsaxena93** [Shopify/eslint-plugin-shopify#142]
Running lint on this file https://github.com/Shopify/online-store-web/pull/893/files#diff-c43e4dc1f934bc937bc5b0a810d6412cR1 leads to `react/no-this-in-sfc` eslint failures. `error: Stateless functional components should not use this`. This is obviously incorrect since this module has nothing to do with React.

**Comment by bernardofd** [comment]
Sorry, just realized I was in the wrong repo. This should be an issue in https://github.com/yannickcr/eslint-plugin-react

**Comment by alexandcote** [comment]
Issue should be fixed.
