### ISSUE TITLE
strict-component-boundaries possibly flagging incorrectly

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/eslint-plugin-shopify#156]
I can't tell if the `strict-component-boundaries` rule is working as intended in this case. These are utils, not components.

Here's the [errors in CI](https://circleci.com/gh/Shopify/images/29?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for this [code](https://github.com/Shopify/images/pull/10/commits/d36cf94db2fafb60fc743ae1dbf9eaf884db039e). 

If this isn't a bug, please close this.
cc/ @cartogram

**Comment by cartogram** [comment]
@ismail-syed looks like a bug to me. I'll put together a fix.

**Comment by BPScott** [comment]
I'm getting errors on lines that looks like: `import './styles/global.scss';` and `import * as styles from './VisuallyHidden.scss';` which are also false positives.

**Comment by cartogram** [comment]
@BPScott what repo are you seeing that? Polaris?

**Comment by BPScott** [comment]
Yep in polaris-react. Check the linting output in https://github.com/Shopify/polaris-react/pull/2240

**Comment by cartogram** [comment]
@BPScott thanks! I have a PR up and will make sure to tophat in that repo before merging.
