### ISSUE TITLE
Replace typescript-eslint-parser with @typescript-eslint/parser

### ISSUE THREAD

**Issue by tleunen** [Shopify/eslint-plugin-shopify#218]
cf. https://eslint.org/blog/2019/01/future-typescript-eslint

ESLint recently released a note saying that the current typescript-eslint-parser is now archived and we should use the new `@typescript-eslint/parser` instead. 
https://github.com/typescript-eslint/typescript-eslint

**Comment by ismail-syed** [comment]
> The version range of TypeScript currently supported by this parser is >=3.2.1 <3.4.0.

Web's still on TS 3.0.1. Pushing this forward will likely help push web upgrading to a newer release of TS. Not sure where other projects are at but keeping these tools up to date helps encourage/force other org-wide projects to update.

**Comment by cartogram** [comment]
Closed in https://github.com/Shopify/eslint-plugin-shopify/pull/233
