### ISSUE TITLE
Rule for no `if` statements in tests

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#227]

**Comment by cartogram** [comment]
This should do it: https://astexplorer.net/#/gist/55f61680ccc7e5c4e876d29fe2b3f56f/a55b5d7d16eb2c59974c5dd2e03b5155ad90cc5a, but an alternate approach would be to look for visits on a test statement and then look in the body for `ifStatement`s.

Not sure what would work better TBH.
