### ISSUE TITLE
Add lint rule for "what do I return from a hook?"

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#234]
Or, just a best practice guide, if we can't do a linting rule.

**Comment by cartogram** [comment]
Just a start, but here is a basic check for max 'things' returned. 
https://astexplorer.net/#/gist/b015f5cd1b41b049f2feffdff6d9f3a9/a616e30f1d02733e274d6c96133d285c6450ecec
Could build on this to limit returning only objects or only arrays under certain circumstances.

**Comment by cartogram** [comment]
https://astexplorer.net/#/gist/b015f5cd1b41b049f2feffdff6d9f3a9/2d1b13e4e01e1a2d90b6b2b4168793f1f3a2953a
