### ISSUE TITLE
Add security plugin

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#24]
Seems like a no-brained for the node preset.

https://github.com/nodesecurity/eslint-plugin-security/blob/master/README.md

**Comment by GoodForOneFare** [comment]
See also https://github.com/Shopify/tslint-config-shopify/issues/60.

**Comment by alexandcote** [comment]
I'm closing this 3 years old issue. Feel free to reopen it if you think this is still relevant.
