### ISSUE TITLE
Update to eslint@4

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#32]

**Comment by lemonmade** [comment]
With 4.1, there's even more niceness to take advantage of: config overrides in particular are really great for the collocated tests we are leaning towards.

**Comment by kaelig** [comment]
What needs to happen for this to be done?

**Comment by GoodForOneFare** [comment]
FED tooling needs 2 more team members.

Failing that, someone has to:
* Run through `yarn run rules-status`/`yarn run rules-omitted` and figure out what's missing/deprecated
* Submit a PR with new rules ([PRs look like this](https://github.com/Shopify/eslint-plugin-shopify/pull/27/files))
* Run new rules in common projects and assess the impact on Shopify devs
* Build consensus with JS devs on rule changes
* Follow up with config bumps in core projects

Looking forward to your PR, @kaelig!

**Comment by GoodForOneFare** [comment]
Done in https://github.com/Shopify/eslint-plugin-shopify/pull/34
