### ISSUE TITLE
Possibly add ignorePureComponents flag to react/prefer-stateless-function

### ISSUE THREAD

**Issue by nathanmarks** [Shopify/eslint-plugin-shopify#5]
@lemonmade 

WDYT to adding the `ignorePureComponents` flag to `react/prefer-stateless-function`? Enabling the flag will still result in an error if you aren't actually using props etc in the component.

Unless you'd rather deter people from using it and recommend they implement scu themselves / use a hoc.

Right now, our `eslint` config spits out an error if you extend `React.PureComponent`.

**Comment by lemonmade** [comment]
cc/ @GoodForOneFare @ismail-syed, I don't see a problem with adding that option.

**Comment by GoodForOneFare** [comment]
Works for me.  @ismail-syed, can you fit this into your current PR?

**Comment by ismail-syed** [comment]
@GoodForOneFare Will do.

**Comment by ismail-syed** [comment]
Added: https://github.com/Shopify/eslint-plugin-shopify/pull/4
💯
