### ISSUE TITLE
Add eslint-plugin-jsx-a11y

### ISSUE THREAD

**Issue by kaelig** [Shopify/eslint-plugin-shopify#51]
See https://www.npmjs.com/package/eslint-plugin-jsx-a11y

I've been meaning to use it on polaris-styleguide but it probably would be even better if it was embedded in our default config.

@svinkle is this something you'd be interested in taking on?

**Comment by GoodForOneFare** [comment]
Isn't this already in the react config?

[rule config](https://github.com/Shopify/eslint-plugin-shopify/blob/179011946e71aea6a69a07c4ab65edb9e543a491/lib/config/rules/jsx-a11y.js)
[rule import](https://github.com/Shopify/eslint-plugin-shopify/blob/179011946e71aea6a69a07c4ab65edb9e543a491/lib/config/react.js#L27)

**Comment by svinkle** [comment]
Agree with @GoodForOneFare; looks like it's all in the config.

**Comment by kaelig** [comment]
Thanks, I guess I got confused because in polaris-styleguide it doesn't seem to be linting *.tsx files. Any tips to configure it to get that working?

**Comment by GoodForOneFare** [comment]
`.tsx` files are linted by tslint.  You can either:
- Wait for @ismail-syed to finish his active investigation into eslint/typescript
- Find a good jsx/a11y plugin for tslint and add it to [`tslint-config-shopify`](https://github.com/Shopify/tslint-config-shopify)

If Ismail's investigation is successful, our tslint config will be 🔥 (or its role will be greatly diminished).
