### ISSUE TITLE
Cannot Find Module eslint-plugin-shopify

### ISSUE THREAD

**Issue by manavm1990** [Shopify/eslint-plugin-shopify#57]
`npm install eslint-plugin-shopify --save-dev
npm WARN typescript-eslint-parser@9.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN lily236@0.0.1 No description
npm WARN lily236@0.0.1 No repository field.
npm WARN lily236@0.0.1 No license field.

+ eslint-plugin-shopify@18.1.0
updated 1 package in 9.185s`

I also see the folder inside node_modules. 

However, I keep seeing: 

> Cannot Find Module eslint-plugin-shopify

.eslintrc is:
`{
  "extends": [
    "plugin:shopify/esnext",
    "plugin:shopify/jquery",
    "plugin:shopify/prettier"
  ]
}`

**Comment by manavm1990** [comment]
Actually now, it says: Error while running ESLint: Cannot read config file: .../node_modules/eslint-plugin-shopify/index.js

**Comment by lemonmade** [comment]
I think this should be fixed in the latest patch update, sorry for the issue.
