### ISSUE TITLE
Rework plugins for TS/ JS world

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#62]
Over the break, I found it very annoying that, in Web (a TS-mostly project), any JS file I was editing had a lesser linting experience: any rules that we turned off because TS handles them were still turned off for JS. I think we can make this better by reworking how our configs are done. We should be able to use [glob patterns](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) to have a single `plugin:shopify` (or similar) config that does what our `esnext` config does now, and provides overrides for .ts(x)? files. Similarly, we should update our ava/ mocha configs to only apply to test files (this might not be entirely possible if we don't have a common pattern, but if we ever add a Jest-specific config we could do it using the known .test.js|ts|tsx pattern).

cc/ @ismail-syed @GoodForOneFare

**Comment by alexandcote** [comment]
I'm closing this 2 years old issue. Feel free to reopen it if you think this is still relevant.
