### ISSUE TITLE
Add more React and Enzyme rules

### ISSUE THREAD

**Issue by lemonmade** [Shopify/eslint-plugin-shopify#77]
* No useless wrappers (`<>{stuff}{andThings}</>` > `<div>{stuff}{andThings}</div>`)
* React component should make every member private except React API stuff
* Enzyme no bad features (`setState`, `instance`, etc)
* Don't reach across component boundaries (good: `./components`, `../components`, `components`, `../OtherComponent`. bad: `../OtherComponent/any-path`, `./components/SomeComponent`)
* Avoid `renderFoo` methods being explicitly called in `render()` (use components instead)
* Avoid using most raw DOM manipulation
* Avoid the word `correct` in test names

**Comment by alexandcote** [comment]
Most of the issues listed above are now solve. Feel free to reopen an issue if I missed something.
