### ISSUE TITLE
Add ESLint config validation tests

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#8]
Originally raised by @lemonmade in the JS repo:
> https://github.com/scottnonnenberg/eslint-config-thehelp/blob/3eaed6cda4e14c10df6609885361776c28691a70/scripts/validate.js#L5-L11
>
> The whole repo is also an interesting look at setting up a custom config.

**Comment by alexandcote** [comment]
I'm closing this 3 years old issue. Feel free to reopen it if you think this is still relevant.
