### ISSUE TITLE
Look at adding a few more ESLint plugins

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#9]
Originally raised by @lemonmade [in the JS repo](https://github.com/Shopify/javascript/issues/223):
> https://github.com/sindresorhus/eslint-plugin-unicorn
> https://github.com/apollostack/eslint-plugin-graphql
> https://github.com/jhusain/eslint-plugin-immutable
> https://www.npmjs.com/package/eslint-plugin-no-loops

**Comment by alexandcote** [comment]
I'm closing this 3 years old issue. Feel free to reopen it if you think this is still relevant.
